version: '3'

services:
  database:    
    image: 'postgres:14.7'
    container_name: postgres14
    ports:
      - 25432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - .\db-data14\:/var/lib/postgresql/data/
      - .\init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4014
    ports:
      - 25433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data14/:/var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge
